pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Tuongtapcode/DemoQLDA.git'
            }
        }

        stage('Hello') {
            steps {
                echo '✅ Jenkins pipeline is working!'
                sh 'ls -la'
            }
        }
    }
}
