name: CI/CD to Render

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: nguyentuong/demoqlda

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Build Docker image
      - name: Build Docker image
        run: |
          cd MuonTraSach
          docker build -t $IMAGE_NAME:${{ github.run_number }} .
          docker tag $IMAGE_NAME:${{ github.run_number }} $IMAGE_NAME:latest

      # 3. Run tests
      - name: Run Unit Tests
        run: |
          cd MuonTraSach
          docker run --rm $IMAGE_NAME:${{ github.run_number }} python -m unittest discover -s MuonTraSach/tests

      # 4. Login & Push Docker (only on main)
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }} 

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push $IMAGE_NAME:${{ github.run_number }}
          docker push $IMAGE_NAME:latest

      # 5. Trigger Render Deploy Hook
      - name: Trigger Render Deploy
        if: github.ref == 'refs/heads/main'
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
